# Catalog Custom Values
image:
  pullPolicy: Always

resources:
  requests:
    cpu: "128m"
    memory: "128Mi"
  limits:
    memory: "256Mi"

mysql:
  create: true
  image:
    repository: public.ecr.aws/docker/library/mysql
    pullPolicy: IfNotPresent
    tag: "8.0"
  service:
    type: ClusterIP
    port: 3306
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistentVolume:
    enabled: false
    annotations: {}
    labels: {}
    accessModes:
      - ReadWriteOnce
    size: 10Gi

app:
  persistence:
    provider: mysql
    endpoint: ""
    database: "catalog"

    secret:
      create: true
      name: catalog-db
      username: mydbadmin
      password: german123