# Application Settings
app:
  theme: green # Other options: orange, default, green, teal


# Ingress for load balancer
ingress:
  enabled: true
  className: alb
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
  tls: []
  hosts: []

# Add Image and Tag
image:
  repository: public.ecr.aws/i5b4r2o0/retail-fenix/ui
  pullPolicy: Always
  tag: "1.0.0"
 

# Release Info
releaseInfo:
  enabled: true
 

