services:

  ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - catalog
      - cart
      - orders
      - checkout
    environment:
      - NODE_ENV=production

  catalog:
    build:
      context: ./src/catalog
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  cart:
    build:
      context: ./src/cart
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  orders:
    build:
      context: ./src/orders
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

  checkout:
    build:
      context: ./src/checkout
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
