FROM golang:1.24-alpine

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod tidy
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOTOOLCHAIN=local go build -o catalog .

EXPOSE 8080
CMD ["./catalog"]
