apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retail-fenix.fullname" . }}
  labels:
    {{- include "retail-fenix.labels" . | nindent 4 }}
data:
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
  RETAIL_CART_PERSISTENCE_PROVIDER: {{ .Values.app.persistence.provider | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: {{ .Values.app.persistence.dynamodb.endpoint | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: {{ .Values.app.persistence.dynamodb.createTable | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: {{ .Values.app.persistence.dynamodb.tableName | quote }}
