mysql:
  create: true

app:
  persistence:
    secret:
      create: true
      name: catalog-db
      username: catalog_user
      password: catalog_pass123

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
