ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

autoscaling:
  enabled: true
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
