replicaCount: 1

image:
  repository: public.ecr.aws/i5b4r2o0/retail-fenix/checkout
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: false
  name: "default"

podSecurityContext:
  runAsNonRoot: true

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: "256m"
    memory: "512Mi"
  limits:
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false

app:
  persistence:
    provider: redis
    redis:
      url: "redis://checkout-redis:6379"
  endpoints:
    orders: "http://orders:8080"
